[package]
name = "insert_dylib_rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "insert_dylib"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
crossterm = "0.27.0"
inquire = "0.6.2"
